#!/usr/bin/python
# This file should be executed along with 'grader pregrade'
# Author: Xinnan Cheng (2017 WT)
# 

import os, hashlib, random, glob

### CHANGE THESE APPROPRIATELY ###
num_grader = 4
##################################

#### OBTAIN THESE FROM GRADER ####
#### Need modification ###########
sem = "Spring2017"
ASSN_TYPE="lab"
num_assn=1
##################################

lab_dir = "grades/"+sem+'/'+ASSN_TYPE+num_assn
grades_dir = "grades/"+sem+'/'+ASSN_TYPE+num_assn+"_grades"
backup_dir = "grades/"+sem+'/'+ASSN_TYPE+num_assn+"_backup"

# the location of annoynmous lab direvtory
lab_redact_dir = "grades/"+sem+"_annoym"+'/'+ASSN_TYPE+num_assn
# the location of annoynmous lab grades (symlink to real lab grades)
grade_redact_dir = "grades/"+sem+"_annoym"+'/'+ASSN_TYPE+num_assn+"_grades"
# the file with all student names
name_list = "grades/"+sem+"/name_list"

# create directories if not exist
if (!os.path.exists(lab_redact_dir)):
	os.makedirs(lab_redact_dir)
if (!os.path.exists(grade_redact_dir)):
	os.makedirs(grade_redact_dir)

###
# deal with annoynmous lab grade file
# make sure everything in grade_name has a symlink in grade_anonym 
###
grade_name = os.listdir(grades_dir)
grade_anonym = os.listdir(grade_redact_dir)

# keep track of student name and their respective hash name
hash_dict = {}

for i in range(len(grade_name)):
	for j in range(len(grade_anonym)):
		if os.path.realpath(grades_dir + '/' + grade_name[i]) \
			== os.path.realpath(grade_redact_dir  + '/' + grade_anonym[j]):
			hash_dict[grade_name[i]] = grade_anonym[j]
			del grade_name[i]
			break

for i in range(len(grade_name)):
	# create a hash_name for each student
	# the first number shows the assignment of the grader
	hash_name = '[' + random.randint(1,num_grader) + ']' + \
				+ hashlib.sha224(grade_name[i]).hexdigest()
	# create symlink for each students' grade file
	os.symlink(grades_dir + '/' + grade_name[i], 
		grade_redact_dir  + '/' + hash_name)
	hash_dict[grade_name[i]] = hash_name

###
# deal with annoynmous lab files 
###
lab_name = glob.glob(lab_dir+"/*."+num_assn+".*/")
lab_anonym = os.listdir(lab_redact_dir)

lab_hash = []
for anon in lab_anonym:
	lab_hash.append(anon.split('.')[0])
lab_time = []
for anon in lab_anonym:
	lab_hash.append(anon.split('.')[2])

# assume that if a student's submission is in lab_dir, 
# then this student also has a grade file already created
for name in lab_name:
	stu_name = name.split('.')[0]
	stu_time = name.split('.')[2]

	# check if one student's submission already has a redacted verison
	try:
		if (hash_dict[stu_name] not in lab_hash) or (stu_time not in lab_time):
			exist = False
		else:
			exist = True
	except KeyError:
		exist = True
		print "There is no grade file for " + stu_name + " !" 

	# create redacted version if not
	if not exist:
		os.mkdir(lab_redact_dir+'/'+hash_dict[stu_name]
			+'.'+num_assn+'.'+stu_time)

		javafiles = []
		readmes = []
		other = []
		for root, dirnames, filenames in os.walk(os.path.join(lab_dir,name)):
			for fname in filenames:
				if fnmatch.fnmatchcase(fname, "*.[Jj][Aa][Vv][Aa]"):
					javafiles.append(os.path.join(root, fname))
				elif fnmatch.fnmatchcase(fname, "*.[Rr][Ee][Aa][Dd][Mm][Ee]"):
					readmes.append(os.path.join(root, fname))
				else:
					other.append(os.path.join(root, fname))




